<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:wsa="http://www.w3.org/2005/08/addressing">
    <soap:Header>
        <wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
        <wsa:From>
            <wsa:Address>https://noded3.test.webservices.amadeus.com/1ASIWFLY7FA</wsa:Address>
        </wsa:From>
        <wsa:Action>http://webservices.amadeus.com/PNRRET_21_1_1A</wsa:Action>
        <wsa:MessageID>urn:uuid:4c54fcaf-61b2-8ba4-5d10-3963c531a0e7</wsa:MessageID>
        <wsa:RelatesTo RelationshipType="http://www.w3.org/2005/08/addressing/reply">
            56c81f14-3a75-4cd8-b616-838bd685b366</wsa:RelatesTo>
        <awsse:Session TransactionStatusCode="InSeries">
            <awsse:SessionId>{{ $SessionId }}</awsse:SessionId>
            <awsse:SequenceNumber>1</awsse:SequenceNumber>
            <awsse:SecurityToken>{{ $SessionToken }}</awsse:SecurityToken>
        </awsse:Session>
    </soap:Header>
    <soap:Body>
        <PNR_Reply xmlns="http://xml.amadeus.com/PNRACC_21_1_1A">
            <pnrHeader>
                <reservationInfo>
                    <reservation>
                        <companyId>1A</companyId>
                        <controlNumber>{{ $ControlNumber }}</controlNumber>
                        <date>171222</date>
                        <time>0539</time>
                    </reservation>
                </reservationInfo>
            </pnrHeader>
            <securityInformation>
                <responsibilityInformation>
                    <typeOfPnrElement>RP</typeOfPnrElement>
                    <agentId>WSSU</agentId>
                    <officeId>BGWIK3334</officeId>
                </responsibilityInformation>
                <queueingInformation>
                    <queueingOfficeId>BGWIK3334</queueingOfficeId>
                </queueingInformation>
                <cityCode>BGW</cityCode>
                <secondRpInformation>
                    <creationOfficeId>BGWIK3334</creationOfficeId>
                    <agentSignature>9999WS</agentSignature>
                    <creationDate>171222</creationDate>
                    <creationTime>0539</creationTime>
                </secondRpInformation>
            </securityInformation>
            <freetextData>
                <freetextDetail>
                    <subjectQualifier>3</subjectQualifier>
                    <type>P12</type>
                </freetextDetail>
                <longFreetext>--- TST RLR MSC ---</longFreetext>
            </freetextData>
            <pnrHeaderTag>
                <statusInformation>
                    <indicator>TST</indicator>
                </statusInformation>
                <statusInformation>
                    <indicator>RLR</indicator>
                </statusInformation>
                <statusInformation>
                    <indicator>MAR</indicator>
                </statusInformation>
            </pnrHeaderTag>
            <sbrPOSDetails>
                <sbrUserIdentificationOwn>
                    <originIdentification>
                        <inHouseIdentification1>BGWIK3334</inHouseIdentification1>
                    </originIdentification>
                    <originatorTypeCode>T</originatorTypeCode>
                </sbrUserIdentificationOwn>
                <sbrSystemDetails>
                    <deliveringSystem>
                        <companyId>1A</companyId>
                        <locationId>BGW</locationId>
                    </deliveringSystem>
                </sbrSystemDetails>
                <sbrPreferences>
                    <userPreferences>
                        <codedCountry>IQ</codedCountry>
                    </userPreferences>
                </sbrPreferences>
            </sbrPOSDetails>
            <sbrCreationPosDetails>
                <sbrUserIdentificationOwn>
                    <originIdentification>
                        <inHouseIdentification1>BGWIK3334</inHouseIdentification1>
                    </originIdentification>
                    <originatorTypeCode>T</originatorTypeCode>
                </sbrUserIdentificationOwn>
                <sbrSystemDetails>
                    <deliveringSystem>
                        <companyId>1A</companyId>
                        <locationId>BGW</locationId>
                    </deliveringSystem>
                </sbrSystemDetails>
                <sbrPreferences>
                    <userPreferences>
                        <codedCountry>IQ</codedCountry>
                    </userPreferences>
                </sbrPreferences>
            </sbrCreationPosDetails>
            <sbrUpdatorPosDetails>
                <sbrUserIdentificationOwn>
                    <originIdentification>
                        <inHouseIdentification1>BGWIK3334</inHouseIdentification1>
                    </originIdentification>
                    <originatorTypeCode>T</originatorTypeCode>
                </sbrUserIdentificationOwn>
                <sbrSystemDetails>
                    <deliveringSystem>
                        <companyId>1A</companyId>
                        <locationId>BGW</locationId>
                    </deliveringSystem>
                </sbrSystemDetails>
                <sbrPreferences>
                    <userPreferences>
                        <codedCountry>IQ</codedCountry>
                    </userPreferences>
                </sbrPreferences>
            </sbrUpdatorPosDetails>
            <technicalData>
                <enveloppeNumberData>
                    <sequenceDetails>
                        <number>1</number>
                    </sequenceDetails>
                </enveloppeNumberData>
                <lastTransmittedEnvelopeNumber>
                    <currentRecord>0</currentRecord>
                </lastTransmittedEnvelopeNumber>
                <purgeDateData>
                    <dateTime>
                        <year>2023</year>
                        <month>5</month>
                        <day>17</day>
                    </dateTime>
                </purgeDateData>
            </technicalData>
            
            @if (isset($CHD) && $CHD != 0)
                @if ($CHD == 1)
                    <travellerInfo>
                        <elementManagementPassenger>
                            <reference>
                                <qualifier>PT</qualifier>
                                <number>1</number>
                            </reference>
                            <segmentName>NM</segmentName>
                            <lineNumber>1</lineNumber>
                        </elementManagementPassenger>
                        <passengerData>
                            <travellerInformation>
                                <traveller>
                                    <surname>CHILDFAMILYNAMEBYS</surname>
                                    <quantity>1</quantity>
                                </traveller>
                                <passenger>
                                    <firstName>CHILDNAMELJG</firstName>
                                    <type>CHD</type>
                                </passenger>
                            </travellerInformation>
                            <dateOfBirth>
                                <dateAndTimeDetails>
                                    <qualifier>706</qualifier>
                                    <date>03012015</date>
                                </dateAndTimeDetails>
                            </dateOfBirth>
                        </passengerData>
                        <enhancedPassengerData>
                            <enhancedTravellerInformation>
                                <travellerNameInfo>
                                    <quantity>1</quantity>
                                    <type>CHD</type>
                                </travellerNameInfo>
                                <otherPaxNamesDetails>
                                    <nameType>UN</nameType>
                                    <referenceName>Y</referenceName>
                                    <displayedName>Y</displayedName>
                                    <surname>CHILDFAMILYNAMEBYS</surname>
                                    <givenName>CHILDNAMELJG</givenName>
                                </otherPaxNamesDetails>
                            </enhancedTravellerInformation>
                            <dateOfBirthInEnhancedPaxData>
                                <dateAndTimeDetails>
                                    <qualifier>706</qualifier>
                                    <date>03012015</date>
                                </dateAndTimeDetails>
                            </dateOfBirthInEnhancedPaxData>
                        </enhancedPassengerData>
                    </travellerInfo>
                @else
                    @for($i=1;$i <= $CHD;$i++)
                        <travellerInfo>
                            <elementManagementPassenger>
                                <reference>
                                    <qualifier>PT</qualifier>
                                    <number>{{ $i }}</number>
                                </reference>
                                <segmentName>NM</segmentName>
                                <lineNumber>{{ $i }}</lineNumber>
                            </elementManagementPassenger>
                            <passengerData>
                                <travellerInformation>
                                    <traveller>
                                        <surname>CHILDFAMILYNAMEBYS</surname>
                                        <quantity>1</quantity>
                                    </traveller>
                                    <passenger>
                                        <firstName>CHILDNAMELJG</firstName>
                                        <type>CHD</type>
                                    </passenger>
                                </travellerInformation>
                                <dateOfBirth>
                                    <dateAndTimeDetails>
                                        <qualifier>706</qualifier>
                                        <date>03012015</date>
                                    </dateAndTimeDetails>
                                </dateOfBirth>
                            </passengerData>
                            <enhancedPassengerData>
                                <enhancedTravellerInformation>
                                    <travellerNameInfo>
                                        <quantity>1</quantity>
                                        <type>CHD</type>
                                    </travellerNameInfo>
                                    <otherPaxNamesDetails>
                                        <nameType>UN</nameType>
                                        <referenceName>Y</referenceName>
                                        <displayedName>Y</displayedName>
                                        <surname>CHILDFAMILYNAMEBYS</surname>
                                        <givenName>CHILDNAMELJG</givenName>
                                    </otherPaxNamesDetails>
                                </enhancedTravellerInformation>
                                <dateOfBirthInEnhancedPaxData>
                                    <dateAndTimeDetails>
                                        <qualifier>706</qualifier>
                                        <date>03012015</date>
                                    </dateAndTimeDetails>
                                </dateOfBirthInEnhancedPaxData>
                            </enhancedPassengerData>
                        </travellerInfo>
                    @endfor
                @endif

            @endif

            @if (isset($ADT) && $ADT != 0)
                @if ($ADT == 1)
                    <travellerInfo>
                        <elementManagementPassenger>
                            <reference>
                                <qualifier>PT</qualifier>
                                <number>1</number>
                            </reference>
                            <segmentName>NM</segmentName>
                            <lineNumber>1</lineNumber>
                        </elementManagementPassenger>
                        @if (isset($INF) && $INF != 0)
                            @if ($INF == 1)
                                <passengerData>
                                    <travellerInformation>
                                        <traveller>
                                            <surname>CHILDFAMILYNAMEBYS</surname>
                                            <quantity>1</quantity>
                                        </traveller>
                                        <passenger>
                                            <firstName>CHILDNAMELJG</firstName>
                                            <type>INF</type>
                                        </passenger>
                                    </travellerInformation>
                                    <dateOfBirth>
                                        <dateAndTimeDetails>
                                            <qualifier>706</qualifier>
                                            <date>03012015</date>
                                        </dateAndTimeDetails>
                                    </dateOfBirth>
                                </passengerData>
                            @else
                                @for($j=1;$j <= $INF;$j++)
                                    <passengerData>
                                        <travellerInformation>
                                            <traveller>
                                                <surname>CHILDFAMILYNAMEBYS</surname>
                                                <quantity>{{ $i }}</quantity>
                                            </traveller>
                                            <passenger>
                                                <firstName>CHILDNAMELJG</firstName>
                                                <type>INF</type>
                                            </passenger>
                                        </travellerInformation>
                                        <dateOfBirth>
                                            <dateAndTimeDetails>
                                                <qualifier>706</qualifier>
                                                <date>03012015</date>
                                            </dateAndTimeDetails>
                                        </dateOfBirth>
                                    </passengerData>
                                @endfor
                            @endif
                        @endif
                        <passengerData>
                            <travellerInformation>
                                <traveller>
                                    <surname>CHILDFAMILYNAMEBYS</surname>
                                    <quantity>1</quantity>
                                </traveller>
                                <passenger>
                                    <firstName>CHILDNAMELJG</firstName>
                                    <type>ADT</type>
                                </passenger>
                            </travellerInformation>
                            <dateOfBirth>
                                <dateAndTimeDetails>
                                    <qualifier>706</qualifier>
                                    <date>03012015</date>
                                </dateAndTimeDetails>
                            </dateOfBirth>
                        </passengerData>
                        @if (isset($INF) && $INF != 0)
                            @if ($INF == 1)
                                <enhancedPassengerData>
                                    <enhancedTravellerInformation>
                                        <travellerNameInfo>
                                            <quantity>1</quantity>
                                            <type>INF</type>
                                        </travellerNameInfo>
                                        <otherPaxNamesDetails>
                                            <nameType>UN</nameType>
                                            <referenceName>Y</referenceName>
                                            <displayedName>Y</displayedName>
                                            <surname>CHILDFAMILYNAMEBYS</surname>
                                            <givenName>CHILDNAMELJG</givenName>
                                        </otherPaxNamesDetails>
                                    </enhancedTravellerInformation>
                                    <dateOfBirthInEnhancedPaxData>
                                        <dateAndTimeDetails>
                                            <qualifier>706</qualifier>
                                            <date>03012015</date>
                                        </dateAndTimeDetails>
                                    </dateOfBirthInEnhancedPaxData>
                                </enhancedPassengerData>
                            @else
                                @for($j=1;$j <= $INF;$j++)
                                    <enhancedPassengerData>
                                        <enhancedTravellerInformation>
                                            <travellerNameInfo>
                                                <quantity>1</quantity>
                                                <type>INF</type>
                                            </travellerNameInfo>
                                            <otherPaxNamesDetails>
                                                <nameType>UN</nameType>
                                                <referenceName>Y</referenceName>
                                                <displayedName>Y</displayedName>
                                                <surname>CHILDFAMILYNAMEBYS</surname>
                                                <givenName>CHILDNAMELJG</givenName>
                                            </otherPaxNamesDetails>
                                        </enhancedTravellerInformation>
                                        <dateOfBirthInEnhancedPaxData>
                                            <dateAndTimeDetails>
                                                <qualifier>706</qualifier>
                                                <date>03012015</date>
                                            </dateAndTimeDetails>
                                        </dateOfBirthInEnhancedPaxData>
                                    </enhancedPassengerData>
                                @endfor
                            @endif
                        @endif
                        <enhancedPassengerData>
                            <enhancedTravellerInformation>
                                <travellerNameInfo>
                                    <quantity>1</quantity>
                                    <type>ADT</type>
                                </travellerNameInfo>
                                <otherPaxNamesDetails>
                                    <nameType>UN</nameType>
                                    <referenceName>Y</referenceName>
                                    <displayedName>Y</displayedName>
                                    <surname>CHILDFAMILYNAMEBYS</surname>
                                    <givenName>CHILDNAMELJG</givenName>
                                </otherPaxNamesDetails>
                            </enhancedTravellerInformation>
                            <dateOfBirthInEnhancedPaxData>
                                <dateAndTimeDetails>
                                    <qualifier>706</qualifier>
                                    <date>03012015</date>
                                </dateAndTimeDetails>
                            </dateOfBirthInEnhancedPaxData>
                        </enhancedPassengerData>
                    </travellerInfo>
                @else
                    @for($i=1;$i <= $ADT;$i++)
                        <travellerInfo>
                            <elementManagementPassenger>
                                <reference>
                                    <qualifier>PT</qualifier>
                                    <number>{{ $i }}</number>
                                </reference>
                                <segmentName>NM</segmentName>
                                <lineNumber>{{ $i }}</lineNumber>
                            </elementManagementPassenger>
                            @if (isset($INF) && $INF != 0)
                                @for($j=1;$j <= $INF;$j++)
                                    <passengerData>
                                        <travellerInformation>
                                            <traveller>
                                                <surname>CHILDFAMILYNAMEBYS</surname>
                                                <quantity>{{ $j }}</quantity>
                                            </traveller>
                                            <passenger>
                                                <firstName>CHILDNAMELJG</firstName>
                                                <type>INF</type>
                                            </passenger>
                                        </travellerInformation>
                                        <dateOfBirth>
                                            <dateAndTimeDetails>
                                                <qualifier>706</qualifier>
                                                <date>03012015</date>
                                            </dateAndTimeDetails>
                                        </dateOfBirth>
                                    </passengerData>
                                @endfor
                            @endif
                            <passengerData>
                                <travellerInformation>
                                    <traveller>
                                        <surname>CHILDFAMILYNAMEBYS</surname>
                                        <quantity>{{ $i }}</quantity>
                                    </traveller>
                                    <passenger>
                                        <firstName>CHILDNAMELJG</firstName>
                                        <type>ADT</type>
                                    </passenger>
                                </travellerInformation>
                                <dateOfBirth>
                                    <dateAndTimeDetails>
                                        <qualifier>706</qualifier>
                                        <date>03012015</date>
                                    </dateAndTimeDetails>
                                </dateOfBirth>
                            </passengerData>
                            @if (isset($INF) && $INF != 0)
                                @for($j=1;$j <= $INF;$j++)
                                    <enhancedPassengerData>
                                        <enhancedTravellerInformation>
                                            <travellerNameInfo>
                                                <quantity>1</quantity>
                                                <type>INF</type>
                                            </travellerNameInfo>
                                            <otherPaxNamesDetails>
                                                <nameType>UN</nameType>
                                                <referenceName>Y</referenceName>
                                                <displayedName>Y</displayedName>
                                                <surname>CHILDFAMILYNAMEBYS</surname>
                                                <givenName>CHILDNAMELJG</givenName>
                                            </otherPaxNamesDetails>
                                        </enhancedTravellerInformation>
                                        <dateOfBirthInEnhancedPaxData>
                                            <dateAndTimeDetails>
                                                <qualifier>706</qualifier>
                                                <date>03012015</date>
                                            </dateAndTimeDetails>
                                        </dateOfBirthInEnhancedPaxData>
                                    </enhancedPassengerData>
                                @endfor
                            @endif
                            <enhancedPassengerData>
                                <enhancedTravellerInformation>
                                    <travellerNameInfo>
                                        <quantity>1</quantity>
                                        <type>ADT</type>
                                    </travellerNameInfo>
                                    <otherPaxNamesDetails>
                                        <nameType>UN</nameType>
                                        <referenceName>Y</referenceName>
                                        <displayedName>Y</displayedName>
                                        <surname>CHILDFAMILYNAMEBYS</surname>
                                        <givenName>CHILDNAMELJG</givenName>
                                    </otherPaxNamesDetails>
                                </enhancedTravellerInformation>
                                <dateOfBirthInEnhancedPaxData>
                                    <dateAndTimeDetails>
                                        <qualifier>706</qualifier>
                                        <date>03012015</date>
                                    </dateAndTimeDetails>
                                </dateOfBirthInEnhancedPaxData>
                            </enhancedPassengerData>
                        </travellerInfo>
                    @endfor
                @endif
            @endif

            <dataElementsMaster>
                <marker2></marker2>
                <dataElementsIndiv>
                    <elementManagementData>
                        <reference>
                            <qualifier>OT</qualifier>
                            <number>6</number>
                        </reference>
                        <segmentName>AP</segmentName>
                        <lineNumber>4</lineNumber>
                    </elementManagementData>
                    <otherDataFreetext>
                        <freetextDetail>
                            <subjectQualifier>3</subjectQualifier>
                            <type>5</type>
                        </freetextDetail>
                        <longFreetext>BGW 009647733300123 - FLY 4 ALL - A</longFreetext>
                    </otherDataFreetext>
                </dataElementsIndiv>
                <dataElementsIndiv>
                    <elementManagementData>
                        <reference>
                            <qualifier>OT</qualifier>
                            <number>8</number>
                        </reference>
                        <segmentName>TK</segmentName>
                        <lineNumber>5</lineNumber>
                    </elementManagementData>
                    <ticketElement>
                        <ticket>
                            <indicator>OK</indicator>
                            <date>171222</date>
                            <officeId>BGWIK3334</officeId>
                        </ticket>
                    </ticketElement>
                </dataElementsIndiv>
                <dataElementsIndiv>
                    <elementManagementData>
                        <reference>
                            <qualifier>OT</qualifier>
                            <number>7</number>
                        </reference>
                        <segmentName>SSR</segmentName>
                        <lineNumber>6</lineNumber>
                    </elementManagementData>
                    <serviceRequest>
                        <ssr>
                            <type>CTCE</type>
                            <status>HK</status>
                            <quantity>1</quantity>
                            <companyId>A3</companyId>
                            <freeText>KK//FGDFGDF.COM</freeText>
                        </ssr>
                    </serviceRequest>
                    <elementsIndicators>
                        <statusDetails>
                            <indicator>NON</indicator>
                        </statusDetails>
                    </elementsIndicators>
                </dataElementsIndiv>
                <dataElementsIndiv>
                    <elementManagementData>
                        <reference>
                            <qualifier>OT</qualifier>
                            <number>10</number>
                        </reference>
                        <segmentName>FE</segmentName>
                        <lineNumber>7</lineNumber>
                    </elementManagementData>
                    <otherDataFreetext>
                        <freetextDetail>
                            <subjectQualifier>3</subjectQualifier>
                            <type>10</type>
                        </freetextDetail>
                        <longFreetext>PAX VALID ON A3 FLIGHTS ONLY</longFreetext>
                    </otherDataFreetext>
                    <referenceForDataElement>
                        <reference>
                            <qualifier>ST</qualifier>
                            <number>1</number>
                        </reference>
                        <reference>
                            <qualifier>ST</qualifier>
                            <number>2</number>
                        </reference>
                        <reference>
                            <qualifier>PT</qualifier>
                            <number>2</number>
                        </reference>
                    </referenceForDataElement>
                </dataElementsIndiv>
                <dataElementsIndiv>
                    <elementManagementData>
                        <reference>
                            <qualifier>OT</qualifier>
                            <number>9</number>
                        </reference>
                        <segmentName>FP</segmentName>
                        <lineNumber>8</lineNumber>
                    </elementManagementData>
                    <otherDataFreetext>
                        <freetextDetail>
                            <subjectQualifier>3</subjectQualifier>
                            <type>16</type>
                        </freetextDetail>
                        <longFreetext>CASH</longFreetext>
                    </otherDataFreetext>
                </dataElementsIndiv>
                <dataElementsIndiv>
                    <elementManagementData>
                        <reference>
                            <qualifier>OT</qualifier>
                            <number>11</number>
                        </reference>
                        <segmentName>FV</segmentName>
                        <lineNumber>9</lineNumber>
                    </elementManagementData>
                    <otherDataFreetext>
                        <freetextDetail>
                            <subjectQualifier>3</subjectQualifier>
                            <type>P18</type>
                        </freetextDetail>
                        <longFreetext>PAX A3</longFreetext>
                    </otherDataFreetext>
                    <referenceForDataElement>
                        <reference>
                            <qualifier>ST</qualifier>
                            <number>1</number>
                        </reference>
                        <reference>
                            <qualifier>ST</qualifier>
                            <number>2</number>
                        </reference>
                        <reference>
                            <qualifier>PT</qualifier>
                            <number>2</number>
                        </reference>
                    </referenceForDataElement>
                </dataElementsIndiv>
            </dataElementsMaster>
            <tstData>
                <tstGeneralInformation>
                    <generalInformation>
                        <tstReferenceNumber>1</tstReferenceNumber>
                        <tstCreationDate>171222</tstCreationDate>
                    </generalInformation>
                </tstGeneralInformation>
                <tstFreetext>
                    <freetextDetail>
                        <subjectQualifier>3</subjectQualifier>
                        <type>41</type>
                    </freetextDetail>
                    <longFreetext>PAX</longFreetext>
                </tstFreetext>
                <tstFreetext>
                    <freetextDetail>
                        <subjectQualifier>3</subjectQualifier>
                        <type>37</type>
                    </freetextDetail>
                    <longFreetext>LON A3 X/ATH A3 IST42.19NUC42.19END ROE0.876968</longFreetext>
                </tstFreetext>
                <fareBasisInfo>
                    <fareElement>
                        <primaryCode>UNF</primaryCode>
                        <baggageAllowance>0PC</baggageAllowance>
                        <fareBasis>LXLC</fareBasis>
                    </fareElement>
                    <fareElement>
                        <primaryCode>UNF</primaryCode>
                        <connection>X</connection>
                        <baggageAllowance>0PC</baggageAllowance>
                        <fareBasis>LXLC</fareBasis>
                    </fareElement>
                </fareBasisInfo>
                <fareData>
                    <issueIdentifier>F</issueIdentifier>
                    <monetaryInfo>
                        <qualifier>F</qualifier>
                        <amount>37.00</amount>
                        <currencyCode>GBP</currencyCode>
                    </monetaryInfo>
                    <monetaryInfo>
                        <qualifier>E</qualifier>
                        <amount>45.00</amount>
                        <currencyCode>USD</currencyCode>
                    </monetaryInfo>
                    <monetaryInfo>
                        <qualifier>T</qualifier>
                        <amount>132.50</amount>
                        <currencyCode>USD</currencyCode>
                    </monetaryInfo>
                    <taxFields>
                        <taxIndicator>X</taxIndicator>
                        <taxCurrency>USD</taxCurrency>
                        <taxAmount>6.40</taxAmount>
                        <taxCountryCode>YQ</taxCountryCode>
                        <taxNatureCode>AC</taxNatureCode>
                    </taxFields>
                    <taxFields>
                        <taxIndicator>X</taxIndicator>
                        <taxCurrency>USD</taxCurrency>
                        <taxAmount>14.80</taxAmount>
                        <taxCountryCode>YR</taxCountryCode>
                        <taxNatureCode>VB</taxNatureCode>
                    </taxFields>
                    <taxFields>
                        <taxIndicator>X</taxIndicator>
                        <taxCurrency>USD</taxCurrency>
                        <taxAmount>15.90</taxAmount>
                        <taxCountryCode>GB</taxCountryCode>
                        <taxNatureCode>AD</taxNatureCode>
                    </taxFields>
                    <taxFields>
                        <taxIndicator>X</taxIndicator>
                        <taxCurrency>USD</taxCurrency>
                        <taxAmount>28.30</taxAmount>
                        <taxCountryCode>UB</taxCountryCode>
                        <taxNatureCode>AS</taxNatureCode>
                    </taxFields>
                    <taxFields>
                        <taxIndicator>X</taxIndicator>
                        <taxCurrency>USD</taxCurrency>
                        <taxAmount>16.80</taxAmount>
                        <taxCountryCode>WP</taxCountryCode>
                        <taxNatureCode>DP</taxNatureCode>
                    </taxFields>
                    <taxFields>
                        <taxIndicator>X</taxIndicator>
                        <taxCurrency>USD</taxCurrency>
                        <taxAmount>5.30</taxAmount>
                        <taxCountryCode>WQ</taxCountryCode>
                        <taxNatureCode>SE</taxNatureCode>
                    </taxFields>
                </fareData>
                <segmentAssociation>
                    <selection>
                        <option>N</option>
                    </selection>
                    <selection>
                        <option>I</option>
                    </selection>
                </segmentAssociation>
                <referenceForTstData>
                    <reference>
                        <qualifier>PT</qualifier>
                        <number>2</number>
                    </reference>
                    <reference>
                        <qualifier>ST</qualifier>
                        <number>1</number>
                    </reference>
                    <reference>
                        <qualifier>ST</qualifier>
                        <number>2</number>
                    </reference>
                </referenceForTstData>
            </tstData>
            <pricingRecordGroup>
                <pricingRecordData></pricingRecordData>
                <productPricingQuotationRecord>
                    <pricingRecordId>
                        <referenceType>TST</referenceType>
                        <uniqueReference>1</uniqueReference>
                    </pricingRecordId>
                    <passengerTattoos>
                        <passengerReference>
                            <type>PA</type>
                            <value>2</value>
                        </passengerReference>
                    </passengerTattoos>
                    <documentDetailsGroup>
                        <totalFare>
                            <monetaryDetails>
                                <typeQualifier>T</typeQualifier>
                                <amount>132.50</amount>
                                <currency>USD</currency>
                            </monetaryDetails>
                        </totalFare>
                        <issueIdentifier>
                            <priceTicketDetails>
                                <indicators>I</indicators>
                            </priceTicketDetails>
                            <priceTariffType>F</priceTariffType>
                        </issueIdentifier>
                        <manualIndicator>
                            <statusDetails>
                                <indicator>M</indicator>
                                <action>N</action>
                            </statusDetails>
                        </manualIndicator>
                        <officeInformation>
                            <originIdentification>
                                <inHouseIdentification1>BGWIK3334</inHouseIdentification1>
                                <inHouseIdentification2>WS</inHouseIdentification2>
                            </originIdentification>
                        </officeInformation>
                        <creationDate>
                            <businessSemantic>CRD</businessSemantic>
                            <dateTime>
                                <year>2022</year>
                                <month>12</month>
                                <day>17</day>
                            </dateTime>
                        </creationDate>
                        <couponDetailsGroup>
                            <productId>
                                <referenceDetails>
                                    <type>ST</type>
                                    <value>1</value>
                                </referenceDetails>
                            </productId>
                        </couponDetailsGroup>
                        <couponDetailsGroup>
                            <productId>
                                <referenceDetails>
                                    <type>ST</type>
                                    <value>2</value>
                                </referenceDetails>
                            </productId>
                        </couponDetailsGroup>
                        <fareComponentDetailsGroup>
                            <fareComponentID>
                                <itemNumberDetails>
                                    <number>1</number>
                                    <type>FAR</type>
                                </itemNumberDetails>
                            </fareComponentID>
                            <marketFareComponent>
                                <boardPointDetails>
                                    <trueLocationId>LON</trueLocationId>
                                </boardPointDetails>
                                <offpointDetails>
                                    <trueLocationId>IST</trueLocationId>
                                </offpointDetails>
                            </marketFareComponent>
                            <monetaryInformation>
                                <monetaryDetails>
                                    <typeQualifier>B</typeQualifier>
                                    <amount>42.19</amount>
                                    <currency>NUC</currency>
                                </monetaryDetails>
                            </monetaryInformation>
                            <componentClassInfo>
                                <fareBasisDetails>
                                    <rateTariffClass>UNFLXLC</rateTariffClass>
                                </fareBasisDetails>
                            </componentClassInfo>
                            <fareQualifiersDetail>
                                <discountDetails>
                                    <fareQualifier>BOR</fareQualifier>
                                </discountDetails>
                            </fareQualifiersDetail>
                            <fareFamilyDetails>
                                <fareFamilyname>FLEX</fareFamilyname>
                            </fareFamilyDetails>
                            <fareFamilyOwner>
                                <companyIdentification>
                                    <otherCompany>A3</otherCompany>
                                </companyIdentification>
                            </fareFamilyOwner>
                            <couponDetailsGroup>
                                <productId>
                                    <referenceDetails>
                                        <type>ST</type>
                                        <value>1</value>
                                    </referenceDetails>
                                </productId>
                            </couponDetailsGroup>
                            <couponDetailsGroup>
                                <productId>
                                    <referenceDetails>
                                        <type>ST</type>
                                        <value>2</value>
                                    </referenceDetails>
                                </productId>
                            </couponDetailsGroup>
                        </fareComponentDetailsGroup>
                    </documentDetailsGroup>
                </productPricingQuotationRecord>
            </pricingRecordGroup>
        </PNR_Reply>
    </soap:Body>
</soap:Envelope>
