<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:wsa="http://www.w3.org/2005/08/addressing">
    <soap:Header>
        <wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
        <wsa:From>
            <wsa:Address>https://noded3.test.webservices.amadeus.com/1ASIWFLY7FA</wsa:Address>
        </wsa:From>
        <wsa:Action>http://webservices.amadeus.com/ITAREQ_05_2_IA</wsa:Action>
        <wsa:MessageID>urn:uuid:28bdc240-b40e-7894-9dfa-e50477a51c36</wsa:MessageID>
        <wsa:RelatesTo RelationshipType="http://www.w3.org/2005/08/addressing/reply">1f3a50d8-c32c-466d-8b4b-6df2f945d088</wsa:RelatesTo>
        <awsse:Session TransactionStatusCode="InSeries">
            <awsse:SessionId>{{ $SessionId }}</awsse:SessionId>
            <awsse:SequenceNumber>1</awsse:SequenceNumber>
            <awsse:SecurityToken>{{ $SessionToken }}</awsse:SecurityToken>
        </awsse:Session>
    </soap:Header>
    <soap:Body>
        <Air_SellFromRecommendationReply xmlns="http://xml.amadeus.com/ITARES_05_2_IA">
            <message>
                <messageFunctionDetails>
                    <messageFunction>183</messageFunction>
                </messageFunctionDetails>
            </message>
            <itineraryDetails>
                <originDestination>
                    <origin>LON</origin>
                    <destination>IST</destination>
                </originDestination>
                <segmentInformation>
                    <flightDetails>
                        <flightDate>
                            <departureDate>120523</departureDate>
                            <departureTime>2215</departureTime>
                            <arrivalDate>130523</arrivalDate>
                            <arrivalTime>0350</arrivalTime>
                            <dateVariation>1</dateVariation>
                        </flightDate>
                        <boardPointDetails>
                            <trueLocationId>LHR</trueLocationId>
                        </boardPointDetails>
                        <offpointDetails>
                            <trueLocationId>ATH</trueLocationId>
                        </offpointDetails>
                        <companyDetails>
                            <marketingCompany>A3</marketingCompany>
                        </companyDetails>
                        <flightIdentification>
                            <flightNumber>609</flightNumber>
                            <bookingClass>U</bookingClass>
                        </flightIdentification>
                        <flightTypeDetails>
                            <flightIndicator>ET</flightIndicator>
                        </flightTypeDetails>
                        <specialSegment>P</specialSegment>
                    </flightDetails>
                    <apdSegment>
                        <legDetails>
                            <equipment>32Q</equipment>
                        </legDetails>
                        <departureStationInfo>
                            <terminal>2</terminal>
                        </departureStationInfo>
                    </apdSegment>
                    <actionDetails>
                        <quantity>3</quantity>
                        <statusCode>OK</statusCode>
                    </actionDetails>
                </segmentInformation>
                <segmentInformation>
                    <flightDetails>
                        <flightDate>
                            <departureDate>130523</departureDate>
                            <departureTime>0820</departureTime>
                            <arrivalDate>130523</arrivalDate>
                            <arrivalTime>0950</arrivalTime>
                        </flightDate>
                        <boardPointDetails>
                            <trueLocationId>ATH</trueLocationId>
                        </boardPointDetails>
                        <offpointDetails>
                            <trueLocationId>IST</trueLocationId>
                        </offpointDetails>
                        <companyDetails>
                            <marketingCompany>A3</marketingCompany>
                        </companyDetails>
                        <flightIdentification>
                            <flightNumber>990</flightNumber>
                            <bookingClass>U</bookingClass>
                        </flightIdentification>
                        <flightTypeDetails>
                            <flightIndicator>ET</flightIndicator>
                        </flightTypeDetails>
                        <specialSegment>P</specialSegment>
                    </flightDetails>
                    <apdSegment>
                        <legDetails>
                            <equipment>320</equipment>
                        </legDetails>
                    </apdSegment>
                    <actionDetails>
                        <quantity>3</quantity>
                        <statusCode>OK</statusCode>
                    </actionDetails>
                </segmentInformation>
            </itineraryDetails>
        </Air_SellFromRecommendationReply>
    </soap:Body>
</soap:Envelope>