<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:wsa="http://www.w3.org/2005/08/addressing">
    <soap:Header>
        <wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
        <wsa:From>
            <wsa:Address>https://noded3.test.webservices.amadeus.com/1ASIWFLY7FA</wsa:Address>
        </wsa:From>
        <wsa:Action>http://webservices.amadeus.com/TIPNRQ_18_1_1A</wsa:Action>
        <wsa:MessageID>urn:uuid:af357a11-56da-0be4-4dcc-eb68cd4b996f</wsa:MessageID>
        <wsa:RelatesTo RelationshipType="http://www.w3.org/2005/08/addressing/reply">9e8a34dd-80db-43cb-8968-66e5310f66bc</wsa:RelatesTo>
        <awsse:Session TransactionStatusCode="InSeries">
            <awsse:SessionId>{{ $SessionId }}</awsse:SessionId>
            <awsse:SequenceNumber>{{ $SessionNumber }}</awsse:SequenceNumber>
            <awsse:SecurityToken>{{ $SessionToken }}</awsse:SecurityToken>
        </awsse:Session>
    </soap:Header>
    <soap:Body>
        <Fare_MasterPricerTravelBoardSearchReply xmlns="http://xml.amadeus.com/FMPTBR_21_4_1A">
            <replyStatus>
                <status>
                    <advisoryTypeInfo>FQX</advisoryTypeInfo>
                </status>
            </replyStatus>
            <conversionRate>
                <conversionRateDetail>
                    <currency>USD</currency>
                </conversionRateDetail>
            </conversionRate>
            <flightIndex>
                <requestedSegmentRef>
                    <segRef>1</segRef>
                </requestedSegmentRef>
                <groupOfFlights>
                    <propFlightGrDetail>
                        <flightProposal>
                            <ref>1</ref>
                        </flightProposal>
                        <flightProposal>
                            <ref>1320</ref>
                            <unitQualifier>EFT</unitQualifier>
                        </flightProposal>
                        <flightProposal>
                            <ref>UX</ref>
                            <unitQualifier>MCX</unitQualifier>
                        </flightProposal>
                    </propFlightGrDetail>
                    <flightDetails>
                        <flightInformation>
                            <productDateTime>
                                <dateOfDeparture>171222</dateOfDeparture>
                                <timeOfDeparture>2205</timeOfDeparture>
                                <dateOfArrival>181222</dateOfArrival>
                                <timeOfArrival>1110</timeOfArrival>
                                <dateVariation>1</dateVariation>
                            </productDateTime>
                            <location>
                                <locationId>JFK</locationId>
                                <terminal>4</terminal>
                            </location>
                            <location>
                                <locationId>MAD</locationId>
                                <terminal>1</terminal>
                            </location>
                            <companyId>
                                <marketingCarrier>UX</marketingCarrier>
                                <operatingCarrier>UX</operatingCarrier>
                            </companyId>
                            <flightOrtrainNumber>92</flightOrtrainNumber>
                            <productDetail>
                                <equipmentType>788</equipmentType>
                            </productDetail>
                            <addProductDetail>
                                <electronicTicketing>Y</electronicTicketing>
                                <productDetailQualifier>AIP</productDetailQualifier>
                            </addProductDetail>
                        </flightInformation>
                    </flightDetails>
                    <flightDetails>
                        <flightInformation>
                            <productDateTime>
                                <dateOfDeparture>181222</dateOfDeparture>
                                <timeOfDeparture>1500</timeOfDeparture>
                                <dateOfArrival>181222</dateOfArrival>
                                <timeOfArrival>1625</timeOfArrival>
                            </productDateTime>
                            <location>
                                <locationId>MAD</locationId>
                                <terminal>1</terminal>
                            </location>
                            <location>
                                <locationId>LGW</locationId>
                                <terminal>S</terminal>
                            </location>
                            <companyId>
                                <marketingCarrier>UX</marketingCarrier>
                                <operatingCarrier>UX</operatingCarrier>
                            </companyId>
                            <flightOrtrainNumber>1015</flightOrtrainNumber>
                            <productDetail>
                                <equipmentType>73H</equipmentType>
                            </productDetail>
                            <addProductDetail>
                                <electronicTicketing>Y</electronicTicketing>
                                <productDetailQualifier>AIP</productDetailQualifier>
                            </addProductDetail>
                        </flightInformation>
                    </flightDetails>
                </groupOfFlights>
                <groupOfFlights>
                    <propFlightGrDetail>
                        <flightProposal>
                            <ref>2</ref>
                        </flightProposal>
                        <flightProposal>
                            <ref>1020</ref>
                            <unitQualifier>EFT</unitQualifier>
                        </flightProposal>
                        <flightProposal>
                            <ref>FI</ref>
                            <unitQualifier>MCX</unitQualifier>
                        </flightProposal>
                    </propFlightGrDetail>
                    <flightDetails>
                        <flightInformation>
                            <productDateTime>
                                <dateOfDeparture>171222</dateOfDeparture>
                                <timeOfDeparture>1925</timeOfDeparture>
                                <dateOfArrival>181222</dateOfArrival>
                                <timeOfArrival>0615</timeOfArrival>
                                <dateVariation>1</dateVariation>
                            </productDateTime>
                            <location>
                                <locationId>JFK</locationId>
                                <terminal>7</terminal>
                            </location>
                            <location>
                                <locationId>KEF</locationId>
                            </location>
                            <companyId>
                                <marketingCarrier>FI</marketingCarrier>
                                <operatingCarrier>FI</operatingCarrier>
                            </companyId>
                            <flightOrtrainNumber>614</flightOrtrainNumber>
                            <productDetail>
                                <equipmentType>76W</equipmentType>
                            </productDetail>
                            <addProductDetail>
                                <electronicTicketing>Y</electronicTicketing>
                                <productDetailQualifier>AIP</productDetailQualifier>
                            </addProductDetail>
                        </flightInformation>
                    </flightDetails>
                    <flightDetails>
                        <flightInformation>
                            <productDateTime>
                                <dateOfDeparture>181222</dateOfDeparture>
                                <timeOfDeparture>0740</timeOfDeparture>
                                <dateOfArrival>181222</dateOfArrival>
                                <timeOfArrival>1045</timeOfArrival>
                            </productDateTime>
                            <location>
                                <locationId>KEF</locationId>
                            </location>
                            <location>
                                <locationId>LHR</locationId>
                                <terminal>2</terminal>
                            </location>
                            <companyId>
                                <marketingCarrier>FI</marketingCarrier>
                                <operatingCarrier>FI</operatingCarrier>
                            </companyId>
                            <flightOrtrainNumber>450</flightOrtrainNumber>
                            <productDetail>
                                <equipmentType>76W</equipmentType>
                            </productDetail>
                            <addProductDetail>
                                <electronicTicketing>Y</electronicTicketing>
                                <productDetailQualifier>AIP</productDetailQualifier>
                            </addProductDetail>
                        </flightInformation>
                    </flightDetails>
                </groupOfFlights>
                <groupOfFlights>
                    <propFlightGrDetail>
                        <flightProposal>
                            <ref>3</ref>
                        </flightProposal>
                        <flightProposal>
                            <ref>0358</ref>
                            <unitQualifier>EFT</unitQualifier>
                        </flightProposal>
                        <flightProposal>
                            <ref>6X</ref>
                            <unitQualifier>MCX</unitQualifier>
                        </flightProposal>
                    </propFlightGrDetail>
                    <flightDetails>
                        <flightInformation>
                            <productDateTime>
                                <dateOfDeparture>171222</dateOfDeparture>
                                <timeOfDeparture>1500</timeOfDeparture>
                                <dateOfArrival>171222</dateOfArrival>
                                <timeOfArrival>2358</timeOfArrival>
                            </productDateTime>
                            <location>
                                <locationId>JFK</locationId>
                            </location>
                            <location>
                                <locationId>LHR</locationId>
                            </location>
                            <companyId>
                                <marketingCarrier>6X</marketingCarrier>
                                <operatingCarrier>6X</operatingCarrier>
                            </companyId>
                            <flightOrtrainNumber>9306</flightOrtrainNumber>
                            <productDetail>
                                <equipmentType>744</equipmentType>
                            </productDetail>
                            <addProductDetail>
                                <electronicTicketing>Y</electronicTicketing>
                                <productDetailQualifier>AVR</productDetailQualifier>
                            </addProductDetail>
                        </flightInformation>
                    </flightDetails>
                </groupOfFlights>
            </flightIndex>
            <recommendation>
                <itemNumber>
                    <itemNumberId>
                        <number>1</number>
                    </itemNumberId>
                </itemNumber>
                <recPriceInfo>
                    <monetaryDetail>
                        <amount>1305.10</amount>
                    </monetaryDetail>
                    <monetaryDetail>
                        <amount>761.10</amount>
                    </monetaryDetail>
                </recPriceInfo>
                <segmentFlightRef>
                    <referencingDetail>
                        <refQualifier>S</refQualifier>
                        <refNumber>1</refNumber>
                    </referencingDetail>
                    <referencingDetail>
                        <refQualifier>B</refQualifier>
                        <refNumber>1</refNumber>
                    </referencingDetail>
                </segmentFlightRef>
                <paxFareProduct>
                    <paxFareDetail>
                        <paxFareNum>1</paxFareNum>
                        <totalFareAmount>432.40</totalFareAmount>
                        <totalTaxAmount>241.40</totalTaxAmount>
                        <codeShareDetails>
                            <transportStageQualifier>V</transportStageQualifier>
                            <company>UX</company>
                        </codeShareDetails>
                        <pricingTicketing>
                            <priceType>OBF</priceType>
                            <priceType>OBA</priceType>
                            <priceType>OBV</priceType>
                        </pricingTicketing>
                    </paxFareDetail>
                    <paxReference>
                        <ptc>ADT</ptc>
                        <traveller>
                            <ref>1</ref>
                        </traveller>
                        <traveller>
                            <ref>2</ref>
                        </traveller>
                    </paxReference>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>PEN</textSubjectQualifier>
                                <informationType>70</informationType>
                            </freeTextQualification>
                            <description>TICKETS ARE NON-REFUNDABLE</description>
                        </pricingMessage>
                    </fare>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>LTD</textSubjectQualifier>
                                <informationType>40</informationType>
                            </freeTextQualification>
                            <description>LAST TKT DTE</description>
                            <description>10NOV22</description>
                            <description> - SEE ADV PURCHASE</description>
                        </pricingMessage>
                    </fare>
                    <fareDetails>
                        <segmentRef>
                            <segRef>1</segRef>
                        </segmentRef>
                        <groupOfFares>
                            <productInformation>
                                <cabinProduct>
                                    <rbd>Z</rbd>
                                    <cabin>M</cabin>
                                    <avlStatus>9</avlStatus>
                                </cabinProduct>
                                <fareProductDetail>
                                    <fareBasis>ZHYO7L</fareBasis>
                                    <passengerType>ADT</passengerType>
                                    <fareType>RP</fareType>
                                </fareProductDetail>
                                <breakPoint>N</breakPoint>
                            </productInformation>
                        </groupOfFares>
                        <groupOfFares>
                            <productInformation>
                                <cabinProduct>
                                    <rbd>Z</rbd>
                                    <cabin>M</cabin>
                                    <avlStatus>9</avlStatus>
                                </cabinProduct>
                                <fareProductDetail>
                                    <fareBasis>ZHYO7L</fareBasis>
                                    <passengerType>ADT</passengerType>
                                    <fareType>RP</fareType>
                                </fareProductDetail>
                                <breakPoint>Y</breakPoint>
                            </productInformation>
                        </groupOfFares>
                        <majCabin>
                            <bookingClassDetails>
                                <designator>M</designator>
                            </bookingClassDetails>
                        </majCabin>
                    </fareDetails>
                </paxFareProduct>
                <paxFareProduct>
                    <paxFareDetail>
                        <paxFareNum>2</paxFareNum>
                        <totalFareAmount>384.40</totalFareAmount>
                        <totalTaxAmount>241.40</totalTaxAmount>
                        <codeShareDetails>
                            <transportStageQualifier>V</transportStageQualifier>
                            <company>UX</company>
                        </codeShareDetails>
                        <pricingTicketing>
                            <priceType>OBF</priceType>
                            <priceType>OBA</priceType>
                            <priceType>OBV</priceType>
                        </pricingTicketing>
                    </paxFareDetail>
                    <paxReference>
                        <ptc>CH</ptc>
                        <traveller>
                            <ref>3</ref>
                        </traveller>
                    </paxReference>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>PEN</textSubjectQualifier>
                                <informationType>70</informationType>
                            </freeTextQualification>
                            <description>TICKETS ARE NON-REFUNDABLE</description>
                        </pricingMessage>
                    </fare>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>LTD</textSubjectQualifier>
                                <informationType>40</informationType>
                            </freeTextQualification>
                            <description>LAST TKT DTE</description>
                            <description>10NOV22</description>
                            <description> - SEE ADV PURCHASE</description>
                        </pricingMessage>
                    </fare>
                    <fareDetails>
                        <segmentRef>
                            <segRef>1</segRef>
                        </segmentRef>
                        <groupOfFares>
                            <productInformation>
                                <cabinProduct>
                                    <rbd>Z</rbd>
                                    <cabin>M</cabin>
                                    <avlStatus>9</avlStatus>
                                </cabinProduct>
                                <fareProductDetail>
                                    <fareBasis>ZHYO7L</fareBasis>
                                    <passengerType>CH</passengerType>
                                    <fareType>RP</fareType>
                                </fareProductDetail>
                                <breakPoint>N</breakPoint>
                            </productInformation>
                            <ticketInfos>
                                <additionalFareDetails>
                                    <ticketDesignator>CH</ticketDesignator>
                                </additionalFareDetails>
                            </ticketInfos>
                        </groupOfFares>
                        <groupOfFares>
                            <productInformation>
                                <cabinProduct>
                                    <rbd>Z</rbd>
                                    <cabin>M</cabin>
                                    <avlStatus>9</avlStatus>
                                </cabinProduct>
                                <fareProductDetail>
                                    <fareBasis>ZHYO7L</fareBasis>
                                    <passengerType>CH</passengerType>
                                    <fareType>RP</fareType>
                                </fareProductDetail>
                                <breakPoint>Y</breakPoint>
                            </productInformation>
                            <ticketInfos>
                                <additionalFareDetails>
                                    <ticketDesignator>CH</ticketDesignator>
                                </additionalFareDetails>
                            </ticketInfos>
                        </groupOfFares>
                        <majCabin>
                            <bookingClassDetails>
                                <designator>M</designator>
                            </bookingClassDetails>
                        </majCabin>
                    </fareDetails>
                </paxFareProduct>
                <paxFareProduct>
                    <paxFareDetail>
                        <paxFareNum>3</paxFareNum>
                        <totalFareAmount>55.90</totalFareAmount>
                        <totalTaxAmount>36.90</totalTaxAmount>
                        <codeShareDetails>
                            <transportStageQualifier>V</transportStageQualifier>
                            <company>UX</company>
                        </codeShareDetails>
                        <pricingTicketing>
                            <priceType>OBF</priceType>
                            <priceType>OBA</priceType>
                            <priceType>OBV</priceType>
                        </pricingTicketing>
                    </paxFareDetail>
                    <paxReference>
                        <ptc>INF</ptc>
                        <traveller>
                            <ref>1</ref>
                            <infantIndicator>1</infantIndicator>
                        </traveller>
                    </paxReference>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>PEN</textSubjectQualifier>
                                <informationType>70</informationType>
                            </freeTextQualification>
                            <description>TICKETS ARE NON-REFUNDABLE</description>
                        </pricingMessage>
                    </fare>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>LTD</textSubjectQualifier>
                                <informationType>40</informationType>
                            </freeTextQualification>
                            <description>LAST TKT DTE</description>
                            <description>10NOV22</description>
                            <description> - SEE ADV PURCHASE</description>
                        </pricingMessage>
                    </fare>
                    <fareDetails>
                        <segmentRef>
                            <segRef>1</segRef>
                        </segmentRef>
                        <groupOfFares>
                            <productInformation>
                                <cabinProduct>
                                    <rbd>Z</rbd>
                                    <cabin>M</cabin>
                                    <avlStatus>9</avlStatus>
                                </cabinProduct>
                                <fareProductDetail>
                                    <fareBasis>ZHYO7L</fareBasis>
                                    <passengerType>IN</passengerType>
                                    <fareType>RP</fareType>
                                </fareProductDetail>
                                <breakPoint>N</breakPoint>
                            </productInformation>
                            <ticketInfos>
                                <additionalFareDetails>
                                    <ticketDesignator>IN</ticketDesignator>
                                </additionalFareDetails>
                            </ticketInfos>
                        </groupOfFares>
                        <groupOfFares>
                            <productInformation>
                                <cabinProduct>
                                    <rbd>Z</rbd>
                                    <cabin>M</cabin>
                                    <avlStatus>9</avlStatus>
                                </cabinProduct>
                                <fareProductDetail>
                                    <fareBasis>ZHYO7L</fareBasis>
                                    <passengerType>IN</passengerType>
                                    <fareType>RP</fareType>
                                </fareProductDetail>
                                <breakPoint>Y</breakPoint>
                            </productInformation>
                            <ticketInfos>
                                <additionalFareDetails>
                                    <ticketDesignator>IN</ticketDesignator>
                                </additionalFareDetails>
                            </ticketInfos>
                        </groupOfFares>
                        <majCabin>
                            <bookingClassDetails>
                                <designator>M</designator>
                            </bookingClassDetails>
                        </majCabin>
                    </fareDetails>
                </paxFareProduct>
            </recommendation>
            <recommendation>
                <itemNumber>
                    <itemNumberId>
                        <number>2</number>
                    </itemNumberId>
                </itemNumber>
                <recPriceInfo>
                    <monetaryDetail>
                        <amount>1401.90</amount>
                    </monetaryDetail>
                    <monetaryDetail>
                        <amount>418.90</amount>
                    </monetaryDetail>
                </recPriceInfo>
                <segmentFlightRef>
                    <referencingDetail>
                        <refQualifier>S</refQualifier>
                        <refNumber>2</refNumber>
                    </referencingDetail>
                    <referencingDetail>
                        <refQualifier>B</refQualifier>
                        <refNumber>1</refNumber>
                    </referencingDetail>
                </segmentFlightRef>
                <paxFareProduct>
                    <paxFareDetail>
                        <paxFareNum>1</paxFareNum>
                        <totalFareAmount>451.20</totalFareAmount>
                        <totalTaxAmount>131.20</totalTaxAmount>
                        <codeShareDetails>
                            <transportStageQualifier>V</transportStageQualifier>
                            <company>FI</company>
                        </codeShareDetails>
                        <pricingTicketing>
                            <priceType>OBV</priceType>
                        </pricingTicketing>
                    </paxFareDetail>
                    <paxReference>
                        <ptc>ADT</ptc>
                        <traveller>
                            <ref>1</ref>
                        </traveller>
                        <traveller>
                            <ref>2</ref>
                        </traveller>
                    </paxReference>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>PEN</textSubjectQualifier>
                                <informationType>70</informationType>
                            </freeTextQualification>
                            <description>TICKETS ARE NON-REFUNDABLE</description>
                        </pricingMessage>
                    </fare>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>LTD</textSubjectQualifier>
                                <informationType>40</informationType>
                            </freeTextQualification>
                            <description>LAST TKT DTE</description>
                            <description>08NOV22</description>
                            <description> - SEE ADV PURCHASE</description>
                        </pricingMessage>
                    </fare>
                    <fareDetails>
                        <segmentRef>
                            <segRef>1</segRef>
                        </segmentRef>
                        <groupOfFares>
                            <productInformation>
                                <cabinProduct>
                                    <rbd>V</rbd>
                                    <cabin>M</cabin>
                                    <avlStatus>9</avlStatus>
                                </cabinProduct>
                                <fareProductDetail>
                                    <fareBasis>VJ1QUSLT</fareBasis>
                                    <passengerType>ADT</passengerType>
                                    <fareType>RP</fareType>
                                </fareProductDetail>
                                <breakPoint>N</breakPoint>
                            </productInformation>
                        </groupOfFares>
                        <groupOfFares>
                            <productInformation>
                                <cabinProduct>
                                    <rbd>V</rbd>
                                    <cabin>M</cabin>
                                    <avlStatus>9</avlStatus>
                                </cabinProduct>
                                <fareProductDetail>
                                    <fareBasis>VJ1QUSLT</fareBasis>
                                    <passengerType>ADT</passengerType>
                                    <fareType>RP</fareType>
                                </fareProductDetail>
                                <breakPoint>Y</breakPoint>
                            </productInformation>
                        </groupOfFares>
                        <majCabin>
                            <bookingClassDetails>
                                <designator>M</designator>
                            </bookingClassDetails>
                        </majCabin>
                    </fareDetails>
                </paxFareProduct>
                <paxFareProduct>
                    <paxFareDetail>
                        <paxFareNum>2</paxFareNum>
                        <totalFareAmount>397.20</totalFareAmount>
                        <totalTaxAmount>131.20</totalTaxAmount>
                        <codeShareDetails>
                            <transportStageQualifier>V</transportStageQualifier>
                            <company>FI</company>
                        </codeShareDetails>
                        <pricingTicketing>
                            <priceType>OBV</priceType>
                        </pricingTicketing>
                    </paxFareDetail>
                    <paxReference>
                        <ptc>CH</ptc>
                        <traveller>
                            <ref>3</ref>
                        </traveller>
                    </paxReference>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>PEN</textSubjectQualifier>
                                <informationType>70</informationType>
                            </freeTextQualification>
                            <description>TICKETS ARE NON-REFUNDABLE</description>
                        </pricingMessage>
                    </fare>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>LTD</textSubjectQualifier>
                                <informationType>40</informationType>
                            </freeTextQualification>
                            <description>LAST TKT DTE</description>
                            <description>08NOV22</description>
                            <description> - SEE ADV PURCHASE</description>
                        </pricingMessage>
                    </fare>
                    <fareDetails>
                        <segmentRef>
                            <segRef>1</segRef>
                        </segmentRef>
                        <groupOfFares>
                            <productInformation>
                                <cabinProduct>
                                    <rbd>V</rbd>
                                    <cabin>M</cabin>
                                    <avlStatus>9</avlStatus>
                                </cabinProduct>
                                <fareProductDetail>
                                    <fareBasis>VJ1QUSLT</fareBasis>
                                    <passengerType>CH</passengerType>
                                    <fareType>RP</fareType>
                                </fareProductDetail>
                                <breakPoint>N</breakPoint>
                            </productInformation>
                            <ticketInfos>
                                <additionalFareDetails>
                                    <ticketDesignator>CH</ticketDesignator>
                                </additionalFareDetails>
                            </ticketInfos>
                        </groupOfFares>
                        <groupOfFares>
                            <productInformation>
                                <cabinProduct>
                                    <rbd>V</rbd>
                                    <cabin>M</cabin>
                                    <avlStatus>9</avlStatus>
                                </cabinProduct>
                                <fareProductDetail>
                                    <fareBasis>VJ1QUSLT</fareBasis>
                                    <passengerType>CH</passengerType>
                                    <fareType>RP</fareType>
                                </fareProductDetail>
                                <breakPoint>Y</breakPoint>
                            </productInformation>
                            <ticketInfos>
                                <additionalFareDetails>
                                    <ticketDesignator>CH</ticketDesignator>
                                </additionalFareDetails>
                            </ticketInfos>
                        </groupOfFares>
                        <majCabin>
                            <bookingClassDetails>
                                <designator>M</designator>
                            </bookingClassDetails>
                        </majCabin>
                    </fareDetails>
                </paxFareProduct>
                <paxFareProduct>
                    <paxFareDetail>
                        <paxFareNum>3</paxFareNum>
                        <totalFareAmount>102.30</totalFareAmount>
                        <totalTaxAmount>25.30</totalTaxAmount>
                        <codeShareDetails>
                            <transportStageQualifier>V</transportStageQualifier>
                            <company>FI</company>
                        </codeShareDetails>
                        <pricingTicketing>
                            <priceType>OBV</priceType>
                        </pricingTicketing>
                    </paxFareDetail>
                    <paxReference>
                        <ptc>INF</ptc>
                        <traveller>
                            <ref>1</ref>
                            <infantIndicator>1</infantIndicator>
                        </traveller>
                    </paxReference>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>PEN</textSubjectQualifier>
                                <informationType>70</informationType>
                            </freeTextQualification>
                            <description>TICKETS ARE NON-REFUNDABLE</description>
                        </pricingMessage>
                    </fare>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>LTD</textSubjectQualifier>
                                <informationType>40</informationType>
                            </freeTextQualification>
                            <description>LAST TKT DTE</description>
                            <description>08NOV22</description>
                            <description> - SEE ADV PURCHASE</description>
                        </pricingMessage>
                    </fare>
                    <fareDetails>
                        <segmentRef>
                            <segRef>1</segRef>
                        </segmentRef>
                        <groupOfFares>
                            <productInformation>
                                <cabinProduct>
                                    <rbd>V</rbd>
                                    <cabin>M</cabin>
                                    <avlStatus>9</avlStatus>
                                </cabinProduct>
                                <fareProductDetail>
                                    <fareBasis>VJ1QUSLT</fareBasis>
                                    <passengerType>IN</passengerType>
                                    <fareType>RP</fareType>
                                </fareProductDetail>
                                <breakPoint>N</breakPoint>
                            </productInformation>
                            <ticketInfos>
                                <additionalFareDetails>
                                    <ticketDesignator>IN</ticketDesignator>
                                </additionalFareDetails>
                            </ticketInfos>
                        </groupOfFares>
                        <groupOfFares>
                            <productInformation>
                                <cabinProduct>
                                    <rbd>V</rbd>
                                    <cabin>M</cabin>
                                    <avlStatus>9</avlStatus>
                                </cabinProduct>
                                <fareProductDetail>
                                    <fareBasis>VJ1QUSLT</fareBasis>
                                    <passengerType>IN</passengerType>
                                    <fareType>RP</fareType>
                                </fareProductDetail>
                                <breakPoint>Y</breakPoint>
                            </productInformation>
                            <ticketInfos>
                                <additionalFareDetails>
                                    <ticketDesignator>IN</ticketDesignator>
                                </additionalFareDetails>
                            </ticketInfos>
                        </groupOfFares>
                        <majCabin>
                            <bookingClassDetails>
                                <designator>M</designator>
                            </bookingClassDetails>
                        </majCabin>
                    </fareDetails>
                </paxFareProduct>
            </recommendation>
            <recommendation>
                <itemNumber>
                    <itemNumberId>
                        <number>3</number>
                    </itemNumberId>
                </itemNumber>
                <recPriceInfo>
                    <monetaryDetail>
                        <amount>2261.20</amount>
                    </monetaryDetail>
                    <monetaryDetail>
                        <amount>101.20</amount>
                    </monetaryDetail>
                </recPriceInfo>
                <segmentFlightRef>
                    <referencingDetail>
                        <refQualifier>S</refQualifier>
                        <refNumber>3</refNumber>
                    </referencingDetail>
                    <referencingDetail>
                        <refQualifier>B</refQualifier>
                        <refNumber>2</refNumber>
                    </referencingDetail>
                </segmentFlightRef>
                <paxFareProduct>
                    <paxFareDetail>
                        <paxFareNum>1</paxFareNum>
                        <totalFareAmount>565.30</totalFareAmount>
                        <totalTaxAmount>25.30</totalTaxAmount>
                        <codeShareDetails>
                            <transportStageQualifier>V</transportStageQualifier>
                            <company>6X</company>
                        </codeShareDetails>
                        <pricingTicketing>
                            <priceType>OBF</priceType>
                            <priceType>OBA</priceType>
                            <priceType>OBV</priceType>
                        </pricingTicketing>
                    </paxFareDetail>
                    <paxReference>
                        <ptc>ADT</ptc>
                        <traveller>
                            <ref>1</ref>
                        </traveller>
                        <traveller>
                            <ref>2</ref>
                        </traveller>
                    </paxReference>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>LTD</textSubjectQualifier>
                                <informationType>41</informationType>
                            </freeTextQualification>
                            <description>LAST TKT DTE</description>
                            <description>17DEC22</description>
                            <description> - DATE OF ORIGIN</description>
                        </pricingMessage>
                    </fare>
                    <fareDetails>
                        <segmentRef>
                            <segRef>1</segRef>
                        </segmentRef>
                        <groupOfFares>
                            <productInformation>
                                <cabinProduct>
                                    <rbd>Y</rbd>
                                    <cabin>M</cabin>
                                    <avlStatus>9</avlStatus>
                                </cabinProduct>
                                <fareProductDetail>
                                    <fareBasis>YLHRNYC</fareBasis>
                                    <passengerType>ADT</passengerType>
                                    <fareType>RP</fareType>
                                </fareProductDetail>
                                <breakPoint>Y</breakPoint>
                            </productInformation>
                        </groupOfFares>
                        <majCabin>
                            <bookingClassDetails>
                                <designator>M</designator>
                            </bookingClassDetails>
                        </majCabin>
                    </fareDetails>
                </paxFareProduct>
                <paxFareProduct>
                    <paxFareDetail>
                        <paxFareNum>2</paxFareNum>
                        <totalFareAmount>565.30</totalFareAmount>
                        <totalTaxAmount>25.30</totalTaxAmount>
                        <codeShareDetails>
                            <transportStageQualifier>V</transportStageQualifier>
                            <company>6X</company>
                        </codeShareDetails>
                        <pricingTicketing>
                            <priceType>OBF</priceType>
                            <priceType>OBA</priceType>
                            <priceType>OBV</priceType>
                        </pricingTicketing>
                    </paxFareDetail>
                    <paxReference>
                        <ptc>CH</ptc>
                        <traveller>
                            <ref>3</ref>
                        </traveller>
                    </paxReference>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>LTD</textSubjectQualifier>
                                <informationType>41</informationType>
                            </freeTextQualification>
                            <description>LAST TKT DTE</description>
                            <description>17DEC22</description>
                            <description> - DATE OF ORIGIN</description>
                        </pricingMessage>
                    </fare>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>APM</textSubjectQualifier>
                                <informationType>5</informationType>
                            </freeTextQualification>
                            <description>NOT FARED AT PASSENGER TYPE REQUESTED *5*</description>
                        </pricingMessage>
                    </fare>
                    <fareDetails>
                        <segmentRef>
                            <segRef>1</segRef>
                        </segmentRef>
                        <groupOfFares>
                            <productInformation>
                                <cabinProduct>
                                    <rbd>Y</rbd>
                                    <cabin>M</cabin>
                                    <avlStatus>9</avlStatus>
                                </cabinProduct>
                                <fareProductDetail>
                                    <fareBasis>YLHRNYC</fareBasis>
                                    <passengerType>ADT</passengerType>
                                    <fareType>RP</fareType>
                                </fareProductDetail>
                                <breakPoint>Y</breakPoint>
                            </productInformation>
                        </groupOfFares>
                        <majCabin>
                            <bookingClassDetails>
                                <designator>M</designator>
                            </bookingClassDetails>
                        </majCabin>
                    </fareDetails>
                </paxFareProduct>
                <paxFareProduct>
                    <paxFareDetail>
                        <paxFareNum>3</paxFareNum>
                        <totalFareAmount>565.30</totalFareAmount>
                        <totalTaxAmount>25.30</totalTaxAmount>
                        <codeShareDetails>
                            <transportStageQualifier>V</transportStageQualifier>
                            <company>6X</company>
                        </codeShareDetails>
                        <pricingTicketing>
                            <priceType>OBF</priceType>
                            <priceType>OBA</priceType>
                            <priceType>OBV</priceType>
                        </pricingTicketing>
                    </paxFareDetail>
                    <paxReference>
                        <ptc>INF</ptc>
                        <traveller>
                            <ref>1</ref>
                            <infantIndicator>1</infantIndicator>
                        </traveller>
                    </paxReference>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>LTD</textSubjectQualifier>
                                <informationType>41</informationType>
                            </freeTextQualification>
                            <description>LAST TKT DTE</description>
                            <description>17DEC22</description>
                            <description> - DATE OF ORIGIN</description>
                        </pricingMessage>
                    </fare>
                    <fare>
                        <pricingMessage>
                            <freeTextQualification>
                                <textSubjectQualifier>APM</textSubjectQualifier>
                                <informationType>5</informationType>
                            </freeTextQualification>
                            <description>NOT FARED AT PASSENGER TYPE REQUESTED *5*</description>
                        </pricingMessage>
                    </fare>
                    <fareDetails>
                        <segmentRef>
                            <segRef>1</segRef>
                        </segmentRef>
                        <groupOfFares>
                            <productInformation>
                                <cabinProduct>
                                    <rbd>Y</rbd>
                                    <cabin>M</cabin>
                                    <avlStatus>9</avlStatus>
                                </cabinProduct>
                                <fareProductDetail>
                                    <fareBasis>YLHRNYC</fareBasis>
                                    <passengerType>ADT</passengerType>
                                    <fareType>RP</fareType>
                                </fareProductDetail>
                                <breakPoint>Y</breakPoint>
                            </productInformation>
                        </groupOfFares>
                        <majCabin>
                            <bookingClassDetails>
                                <designator>M</designator>
                            </bookingClassDetails>
                        </majCabin>
                    </fareDetails>
                </paxFareProduct>
            </recommendation>
            <serviceFeesGrp>
                <serviceTypeInfo>
                    <carrierFeeDetails>
                        <type>FBA</type>
                    </carrierFeeDetails>
                </serviceTypeInfo>
                <serviceCoverageInfoGrp>
                    <itemNumberInfo>
                        <itemNumber>
                            <number>1</number>
                        </itemNumber>
                    </itemNumberInfo>
                    <serviceCovInfoGrp>
                        <paxRefInfo>
                            <travellerDetails>
                                <referenceNumber>1</referenceNumber>
                            </travellerDetails>
                        </paxRefInfo>
                        <coveragePerFlightsInfo>
                            <numberOfItemsDetails>
                                <referenceQualifier>RS</referenceQualifier>
                                <refNum>1</refNum>
                            </numberOfItemsDetails>
                            <lastItemsDetails>
                                <refOfLeg>1</refOfLeg>
                            </lastItemsDetails>
                            <lastItemsDetails>
                                <refOfLeg>2</refOfLeg>
                            </lastItemsDetails>
                        </coveragePerFlightsInfo>
                        <refInfo>
                            <referencingDetail>
                                <refQualifier>F</refQualifier>
                                <refNumber>1</refNumber>
                            </referencingDetail>
                        </refInfo>
                    </serviceCovInfoGrp>
                </serviceCoverageInfoGrp>
                <serviceCoverageInfoGrp>
                    <itemNumberInfo>
                        <itemNumber>
                            <number>2</number>
                        </itemNumber>
                    </itemNumberInfo>
                    <serviceCovInfoGrp>
                        <paxRefInfo>
                            <travellerDetails>
                                <referenceNumber>1</referenceNumber>
                            </travellerDetails>
                        </paxRefInfo>
                        <coveragePerFlightsInfo>
                            <numberOfItemsDetails>
                                <referenceQualifier>RS</referenceQualifier>
                                <refNum>1</refNum>
                            </numberOfItemsDetails>
                            <lastItemsDetails>
                                <refOfLeg>1</refOfLeg>
                            </lastItemsDetails>
                        </coveragePerFlightsInfo>
                        <refInfo>
                            <referencingDetail>
                                <refQualifier>F</refQualifier>
                                <refNumber>2</refNumber>
                            </referencingDetail>
                        </refInfo>
                    </serviceCovInfoGrp>
                </serviceCoverageInfoGrp>
                <globalMessageMarker></globalMessageMarker>
                <freeBagAllowanceGrp>
                    <freeBagAllownceInfo>
                        <baggageDetails>
                            <freeAllowance>0</freeAllowance>
                            <quantityCode>N</quantityCode>
                        </baggageDetails>
                    </freeBagAllownceInfo>
                    <itemNumberInfo>
                        <itemNumberDetails>
                            <number>1</number>
                        </itemNumberDetails>
                    </itemNumberInfo>
                </freeBagAllowanceGrp>
                <freeBagAllowanceGrp>
                    <freeBagAllownceInfo>
                        <baggageDetails>
                            <freeAllowance>8</freeAllowance>
                            <quantityCode>N</quantityCode>
                        </baggageDetails>
                    </freeBagAllownceInfo>
                    <itemNumberInfo>
                        <itemNumberDetails>
                            <number>2</number>
                        </itemNumberDetails>
                    </itemNumberInfo>
                </freeBagAllowanceGrp>
            </serviceFeesGrp>
        </Fare_MasterPricerTravelBoardSearchReply>
    </soap:Body>
</soap:Envelope>